import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner/banner.js'

const handleOnBannerBtnClick = () => {
  console.log('hi banner button');
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText = "Launch" handleOnClick={handleOnBannerBtnClick}/>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
